import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreContextProvider from "@/context/StoreContextProvider";
import Footer from "@/components/Footer";
import ClientNavbar from "@/components/ClientNavbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ToastContainer />
        <div className="w-[80%] mx-auto flex-1 mt-16">
          <StoreContextProvider>
            <section className="mb-5">
              <ClientNavbar />
            </section>
            {children}
          </StoreContextProvider>
        </div>

        <section id="footer" className="w-full">
          <Footer />
        </section>
      </body>
    </html>
  );
}